### ISSUE TITLE
生成两个音频文件时，第二个文件开始报错

### ISSUE THREAD

**Issue by ropz12138** [aliyun/alibabacloud-bailian-speech-demo#1] opened 2024-07-15 12:29 UTC
import os

import dashscope
from dashscope.audio.tts_v2 import AudioFormat, SpeechSynthesizer

if 'DASHSCOPE_API_KEY' in os.environ:
    dashscope.api_key = os.environ['sk-']
else:
    dashscope.api_key = 'sk-'

text_to_synthesize = '欢迎体验阿里云百炼大模型语音合成服务！'
t = 'what are you doing?'
file_to_save = 'result.mp3'

speech_synthesizer = SpeechSynthesizer(
    model='cosyvoice-v1',
    voice='longxiaochun',
    callback=None)

audio_data = speech_synthesizer.call(text_to_synthesize)
print('requestId: ', speech_synthesizer.get_last_request_id())

with open(file_to_save, 'wb') as f:
    f.write(audio_data)

a = speech_synthesizer.call(t)
with open('a.mp3', 'wb') as f:
    f.write(a)

报错：
requestId:  ceb13e4914ae4e868bd1fa7496959c18
Traceback (most recent call last):
  File "/root/wechat_bot_by_ecloud/TTS.py", line 89, in <module>
    f.write(a)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by songguocola** [comment] 2024-07-15 13:07
speech_synthesizer is designed to be non-reusable. In this synchronous calling mode, each time new text needs to be synthesized, a new speech_synthesizer must be created.

If you need to synthesize multiple text segments, you can use the streaming input and streaming output mode. Refer to save_synthesized_audio_to_file_by_streaming_in_streaming_out.py.

speech_synthesizer被设计成不可充用的模式。在同步调用这种模式下，每次合成新的音频需要创建新的speech_synthesizer。
如果你需要连续的合成多段音频，可以使用流式输入流式输出的模式，请参考save_synthesized_audio_to_file_by_streaming_in_streaming_out.py。

**Comment by ropz12138** [comment] 2024-07-19 02:20
好的，谢谢

**Comment by songguocola** [comment] 2024-07-19 02:37
Invocation problem, not a bug, closing the issue.
调用问题，非bug，issue关闭。

**Comment by songguocola** [comment] 2024-07-19 02:37
close

**Closed** 2024-07-19 02:39 UTC
Labels: wontfix
